# Generated by Django 3.2.4 on 2021-07-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bird',
        ),
    ]
