# Generated by Django 3.2.4 on 2021-07-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_delete_bird'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fish',
        ),
    ]
